FROM mongo:6-jammy

LABEL maintainer="Jason Ross <algorythm@gmail.com>"

EXPOSE 27017

ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=secret
ENV MONGO_INITDB_DATABASE=hackerpoints
